-- Migration 0014 — Add preview_text to pitches
--
-- preview_text is the 1-2 sentence inbox teaser shown under the subject line
-- in Gmail/Outlook. Generated by both the Claude path and the heuristic
-- fallback. Nullable so existing rows don't break.

ALTER TABLE pitches
  ADD COLUMN IF NOT EXISTS preview_text text;
